#LAB 3 MAKEFILE

step1demo: lab3_step1.o
	gcc lab3_step1.o -o step1demo 

lab3_step1.o: lab3_step1.c
	gcc -c lab3_step1.c

step2demo: lab3_step2.o
	gcc lab3_step2.o -o step2demo 

lab3_step2.o: lab3_step2.c
	gcc -c lab3_step2.c

step3demo: lab3_step3.o
	gcc lab3_step3.o -o step3demo

lab3_step3.o: lab3_step3.c
	gcc -c lab3_step3.c
clean:
	rm *.o
